#!/usr/bin/env node
/* ============================================================
   FERROUS CAREERS BUILD  v2
   Source of truth: data/jobs.json
   Generates: /careers, /careers/<slug>, careers.css, sitemap.xml
   Injects:   careers band + footer link into the 4 main pages
   Never touches: the nav bar, or anything outside its markers.
   Run: node build.js
   ============================================================ */

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const DATA = JSON.parse(fs.readFileSync(path.join(ROOT, 'data/jobs.json'), 'utf8'));
const { config, companies } = DATA;
const JOBS = DATA.jobs.filter(j => j.live !== false);
const SITE = config.siteUrl.replace(/\/$/, '');
const NAV_LINK = config.navLink === true;   // off by default: the nav bar is already full

const HOST_PAGES = [
  { file: 'index.html',      company: null },
  { file: 'fe/index.html',   company: 'FE' },
  { file: 'de/index.html',   company: 'DE' },
  { file: 'fapl/index.html', company: 'FA' }
];

/* ---------- helpers ---------- */
const read  = f => fs.readFileSync(path.join(ROOT, f), 'utf8');
const write = (f, c) => {
  const p = path.join(ROOT, f);
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, c);
  console.log('  wrote ' + f);
};
const exists = f => fs.existsSync(path.join(ROOT, f));
const esc = s => String(s)
  .replace(/&(?![a-zA-Z#][a-zA-Z0-9]*;)/g, '&amp;')
  .replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const plain = s => String(s).replace(/<[^>]+>/g, '')
  .replace(/&amp;/g, '&').replace(/&reg;/g, '\u00AE')
  .replace(/&middot;/g, '\u00B7').replace(/&rsquo;/g, '\u2019')
  .replace(/&nbsp;/g, ' ').replace(/\s+/g, ' ').trim();

const inr = n => '\u20B9' + Number(n).toLocaleString('en-IN');
const salaryText = j => {
  if (!j.salary || j.salary.min == null) return null;
  const per = (j.salary.unit || 'MONTH').toLowerCase() === 'year' ? '/ year' : '/ month';
  return j.salary.max && j.salary.max !== j.salary.min
    ? `${inr(j.salary.min)} \u2013 ${inr(j.salary.max)} ${per}`
    : `${inr(j.salary.min)} ${per}`;
};
const co = j => companies[j.company];
const jobUrl = j => `/careers/${j.slug}`;          /* cleanUrls:true, trailingSlash:false */
const typeLabel = t => String(t || 'FULL_TIME').replace(/_/g, ' ').toLowerCase()
  .replace(/\b\w/g, m => m.toUpperCase());

function inject(html, name, block, fallback) {
  const s = `<!-- ${name}:START -->`, e = `<!-- ${name}:END -->`;
  const payload = `${s}\n${block}\n${e}`;
  const re = new RegExp(`${s}[\\s\\S]*?${e}`);
  if (re.test(html)) return html.replace(re, payload);
  return fallback(html, payload);
}

/* ---------- harvest the live design system ---------- */
const donor = read('index.html');
const styleBlock  = (donor.match(/<style>[\s\S]*?<\/style>/) || [''])[0];
const navBlock    = (donor.match(/<nav class="main"[\s\S]*?<\/nav>/) || [''])[0];
const footBlock   = (donor.match(/<footer>[\s\S]*?<\/footer>/) || [''])[0];
const fontLinks   = (donor.match(/<link[^>]*fonts\.(googleapis|gstatic|cdnfonts)[^>]*>/g) || []).join('\n');
const analytics   = (donor.match(/<!-- Vercel Web Analytics -->[\s\S]*?speed-insights\/script\.js"><\/script>/) || [''])[0];
const scriptBlock = (donor.match(/<script>\s*\/\/ ===== Ferrous v3 interactions[\s\S]*?<\/script>/) || [''])[0];

if (!styleBlock || !navBlock || !footBlock) {
  console.error('\n  ERROR: could not read <style>, <nav class="main"> or <footer> from index.html.\n');
  process.exit(1);
}

/* nav/footer are copied verbatim. only same-page anchors are made absolute,
   and the "you are here" badge state is cleared. nothing else is altered. */
const navForSub  = navBlock.replace(/href="#/g, 'href="/#').replace(/class="nco here"/g, 'class="nco"');
const footForSub = footBlock.replace(/href="#/g, 'href="/#');

/* ---------- careers.css ---------- */
const CAREERS_CSS = `/* ============ FERROUS CAREERS LAYER ============
   Generated by build.js. Uses the site's own CSS variables and
   component language, so any palette or font change flows through. */

/* ---------------- careers band (on index / fe / de / fapl) ---------------- */
.cband{position:relative;overflow:hidden;padding:0}
.cband-in{position:relative;border-radius:var(--rd);overflow:hidden;
  background:linear-gradient(118deg,#0e0506 0%,var(--red-deep) 34%,var(--red) 58%,#1a070a 100%);
  border:1px solid rgba(168,16,30,.5);padding:52px 48px;
  display:grid;grid-template-columns:1.15fr .85fr;gap:52px;align-items:center}
.cband-in::before{content:'';position:absolute;inset:0;pointer-events:none;
  background:radial-gradient(760px 300px at 12% -10%,rgba(240,79,51,.22),transparent 64%)}
.cband-in::after{content:'';position:absolute;inset:0;pointer-events:none;
  background:repeating-linear-gradient(118deg,rgba(255,255,255,.03) 0 1px,transparent 1px 6px)}
.cb-l,.cb-r{position:relative;z-index:2;min-width:0}
.cb-eyebrow{font-family:var(--data);font-weight:700;font-size:12.5px;letter-spacing:.4em;
  text-transform:uppercase;color:#ffc9be;display:flex;align-items:center;gap:13px;margin-bottom:18px}
.cb-eyebrow::before{content:'';width:30px;height:2px;background:var(--ember);box-shadow:0 0 12px rgba(240,79,51,.9)}
.cb-h{font-family:var(--nulshock);font-size:clamp(22px,3vw,36px);text-transform:uppercase;line-height:1.14;
  color:#fff;text-shadow:0 3px 24px rgba(0,0,0,.55);text-wrap:balance}
.cb-h em{font-style:normal;color:#ffc2b5}
.cb-p{margin-top:14px;font-size:15.5px;line-height:1.65;color:#eccdc7;max-width:490px}
.cb-foot{margin-top:26px;display:flex;align-items:center;gap:18px;flex-wrap:wrap}
.cb-live{display:inline-flex;align-items:center;gap:10px;font-family:var(--data);font-weight:700;
  font-size:12.5px;letter-spacing:.24em;text-transform:uppercase;color:#fff;
  background:rgba(6,3,4,.44);border:1px solid rgba(255,255,255,.24);border-radius:var(--rd-xs);padding:11px 16px}
.cb-dot{width:8px;height:8px;border-radius:50%;background:#59e88a;box-shadow:0 0 11px rgba(89,232,138,.95);
  animation:cb-pulse 2s ease-in-out infinite}
@keyframes cb-pulse{0%,100%{opacity:1;transform:scale(1)}50%{opacity:.4;transform:scale(.72)}}
.cb-band-btn{font-family:var(--data);font-weight:700;font-size:13px;letter-spacing:.2em;text-transform:uppercase;
  padding:14px 28px;border-radius:var(--rd-sm);display:inline-flex;align-items:center;gap:10px;border:0;
  background:#fff;color:#4a0810;box-shadow:0 10px 30px rgba(0,0,0,.4);
  transition:transform .2s ease,box-shadow .25s}
.cb-band-btn::after{content:'\\2192';transition:transform .25s}
.cb-band-btn:hover{transform:translateY(-2px);box-shadow:0 14px 40px rgba(0,0,0,.55)}
.cb-band-btn:hover::after{transform:translateX(5px)}
.cb-r{display:flex;flex-direction:column;gap:10px}
.cb-role{display:flex;align-items:center;gap:15px;padding:16px 18px;border-radius:var(--rd-sm);
  background:rgba(6,3,4,.42);border:1px solid rgba(255,255,255,.16);
  transition:background .28s,border-color .28s,transform .28s}
.cb-role:hover{background:rgba(6,3,4,.7);border-color:rgba(255,255,255,.46);transform:translateX(5px)}
.cb-role .m{flex-shrink:0;font-family:var(--nulshock);font-size:11px;color:#ffc9be;line-height:1;
  border:1px solid rgba(255,255,255,.3);border-radius:var(--rd-xs);padding:7px 9px}
.cb-role .tx{flex:1;min-width:0}
.cb-role .tx b{display:block;font-family:var(--data);font-weight:700;font-size:14.5px;letter-spacing:.07em;
  color:#fff;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.cb-role .tx i{display:block;font-style:normal;font-family:var(--data);font-weight:600;font-size:11.5px;
  letter-spacing:.17em;text-transform:uppercase;color:#e0aba1;margin-top:3px}
.cb-role .go{flex-shrink:0;color:#fff;opacity:.6;transition:opacity .25s,transform .25s}
.cb-role:hover .go{opacity:1;transform:translateX(3px)}
.cb-all{align-self:flex-start;font-family:var(--data);font-weight:700;font-size:11.5px;letter-spacing:.22em;
  text-transform:uppercase;color:#f0c3ba;padding:6px 2px;transition:color .25s}
.cb-all:hover{color:#fff}
.cband-in.empty{background:linear-gradient(118deg,#0c0c0c 0%,#170a0c 48%,#0c0c0c 100%);
  border-color:var(--hairline);grid-template-columns:1fr}
.cband-in.empty .cb-h{color:var(--white)}
.cband-in.empty .cb-h em{color:var(--red-hot)}
.cband-in.empty .cb-p{color:var(--steel-mid);max-width:620px}
.cband-in.empty .cb-eyebrow{color:var(--steel-mid)}
.cband-in.empty .cb-eyebrow::before{background:var(--red-hot)}

/* ---------------- shared bits ---------------- */
.mono{display:inline-flex;align-items:center;gap:9px;border:1px solid #2d2d2d;border-radius:var(--rd-xs);
  padding:7px 12px;background:linear-gradient(178deg,#181818,#101010);transition:border-color .3s,box-shadow .3s}
.mono b{font-family:var(--nulshock);font-size:10.5px;font-weight:400;color:var(--red-hot);letter-spacing:.05em}
.mono i{font-style:normal;font-family:var(--data);font-weight:600;font-size:11.5px;letter-spacing:.15em;
  text-transform:uppercase;color:var(--steel-mid)}
.mono.lg{padding:9px 15px}
.mono.lg b{font-size:12px}
.mono.lg i{font-size:12.5px;color:var(--steel-hi)}

/* metric tiles, same language as the homepage .stats strip */
.mtiles{display:grid;grid-template-columns:repeat(4,1fr);border:1px solid var(--hairline);
  background:var(--coal);border-radius:var(--rd);overflow:hidden;margin-top:34px}
.mtile{padding:26px 22px;border-right:1px solid var(--hairline);position:relative;overflow:hidden;min-width:0}
.mtile:last-child{border-right:0}
.mtile::before{content:'';position:absolute;top:0;left:0;right:0;height:2px;
  background:linear-gradient(90deg,transparent,var(--red-hot),transparent);opacity:0;transition:opacity .4s}
.mtile:hover::before{opacity:1}
.mtile .k{display:flex;align-items:center;gap:8px;font-family:var(--data);font-weight:600;font-size:11px;
  letter-spacing:.24em;text-transform:uppercase;color:var(--steel-low);margin-bottom:11px}
.mtile .v{font-family:var(--data);font-weight:700;font-size:15.5px;letter-spacing:.04em;color:var(--white);line-height:1.35}
.mtile .v.red{color:var(--ember)}
.mtile.accent{background:linear-gradient(160deg,rgba(168,16,30,.15),rgba(110,10,18,.05))}

/* ---------------- careers index ---------------- */
.careers-hero{position:relative;padding:168px 0 76px;overflow:hidden}
.ch-h1{font-family:var(--nulshock);font-size:clamp(29px,5.2vw,62px);text-transform:uppercase;line-height:1.08;
  text-wrap:balance;background:linear-gradient(178deg,#fff 6%,#c9ccd4 32%,#787b85 50%,#e2e4ea 62%,#84878f 90%);
  -webkit-background-clip:text;background-clip:text;-webkit-text-fill-color:transparent}
.ch-cta{margin-top:34px;display:flex;gap:14px;flex-wrap:wrap}

.jfilters{display:flex;gap:9px;flex-wrap:wrap;margin-top:6px}
.jf{font-family:var(--data);font-weight:700;font-size:12.5px;letter-spacing:.18em;text-transform:uppercase;
  color:var(--steel-mid);background:#161616;border:1px solid #2d2d2d;border-radius:var(--rd-xs);
  padding:11px 19px;cursor:pointer;transition:.25s;-webkit-tap-highlight-color:transparent;
  display:inline-flex;align-items:center;gap:9px}
.jf:hover{color:#fff;border-color:#4a4a4a}
.jf.on{color:#fff;border-color:var(--red-hot);background:rgba(125,12,22,.26);box-shadow:0 6px 20px rgba(168,16,30,.2)}
.jf em{font-style:normal;font-family:var(--nulshock);font-size:10px;color:var(--red-hot)}
.jf.on em{color:var(--ember)}

.jgrid{display:grid;grid-template-columns:1fr 1fr;gap:22px;margin-top:30px;perspective:1400px}
.jcard{position:relative;display:flex;flex-direction:column;cursor:pointer;overflow:hidden;
  background:linear-gradient(178deg,var(--plate2),var(--plate));border:1px solid #262626;
  border-radius:var(--rd);padding:34px 32px 30px;transform-style:preserve-3d;will-change:transform;
  transition:transform .25s ease,border-color .35s,box-shadow .35s}
.jcard:hover{border-color:rgba(168,16,30,.6);box-shadow:0 18px 46px rgba(0,0,0,.5)}
.jcard:focus-visible{outline:2px solid var(--red-hot);outline-offset:3px}
.jcard .glow{position:absolute;width:280px;height:280px;border-radius:50%;pointer-events:none;
  background:radial-gradient(circle,rgba(168,16,30,.2),transparent 70%);opacity:0;transition:opacity .35s;
  transform:translate(-50%,-50%)}
.jcard:hover .glow{opacity:1}
.jcard.hide{display:none}
.jc-head{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap}
.jc-exp{font-family:var(--data);font-weight:700;font-size:10.5px;letter-spacing:.22em;text-transform:uppercase;
  color:var(--steel-low);border:1px solid #2d2d2d;border-radius:var(--rd-xs);padding:6px 10px}
.jc-title{font-family:var(--nulshock);font-size:clamp(17px,1.9vw,21px);text-transform:uppercase;line-height:1.22;
  color:var(--white);margin:20px 0 10px}
.jc-sum{font-size:14.5px;line-height:1.62;color:#8f919a;flex:1}
.jc-spec{margin-top:22px;display:grid;border-top:1px solid var(--hairline);border-bottom:1px solid var(--hairline)}
.jc-row{display:flex;justify-content:space-between;align-items:baseline;gap:16px;padding:10px 0;
  border-bottom:1px solid #1a1a1a;font-family:var(--data)}
.jc-row:last-child{border-bottom:0}
.jc-row .k{font-weight:600;font-size:11px;letter-spacing:.22em;text-transform:uppercase;color:var(--steel-low)}
.jc-row .v{font-weight:700;font-size:13px;letter-spacing:.05em;color:var(--white);text-align:right}
.jc-row .v.red{color:var(--ember)}
.jc-go{margin-top:22px;display:flex;align-items:center;justify-content:center;gap:10px;
  font-family:var(--data);font-weight:700;font-size:12.5px;letter-spacing:.2em;text-transform:uppercase;color:#fff;
  padding:14px 16px;border-radius:var(--rd-sm);text-shadow:0 1px 6px rgba(0,0,0,.45);
  background:linear-gradient(110deg,#45060c 0%,var(--red-deep) 26%,var(--red-hot) 50%,var(--red-deep) 74%,#45060c 100%);
  background-size:220% 100%;animation:co-flow 4.2s linear infinite;box-shadow:0 8px 22px rgba(70,6,12,.5);
  transition:box-shadow .25s}
.jc-go::after{content:'\\2192';transition:transform .25s}
.jcard:hover .jc-go{box-shadow:0 12px 32px rgba(92,8,16,.65)}
.jcard:hover .jc-go::after{transform:translateX(5px)}
.jempty{border:1px solid var(--hairline);background:var(--coal);border-radius:var(--rd);
  padding:58px 40px;text-align:center;margin-top:30px}
.jempty h3{font-family:var(--nulshock);font-size:19px;text-transform:uppercase;color:var(--white);margin-bottom:13px}
.jempty p{font-size:15px;line-height:1.7;color:var(--steel-mid);max-width:540px;margin:0 auto}

/* value props on the careers page */
.whyus{display:grid;grid-template-columns:repeat(4,1fr);gap:18px;margin-top:52px}
.whyus .w{background:linear-gradient(178deg,#161616,#0e0e0e);border:1px solid #242424;
  border-radius:var(--rd-sm);padding:28px 26px;position:relative;overflow:hidden;transition:.3s}
.whyus .w::after{content:'';position:absolute;bottom:0;left:0;right:0;height:2px;
  background:linear-gradient(90deg,var(--red-hot),transparent);transform:scaleX(0);transform-origin:left;transition:transform .4s}
.whyus .w:hover{transform:translateY(-5px);border-color:#3c3c3c}
.whyus .w:hover::after{transform:scaleX(1)}
.whyus .n{font-family:var(--nulshock);font-size:13px;color:var(--red-hot);display:block;margin-bottom:12px}
.whyus h3{font-family:var(--data);font-weight:700;font-size:14.5px;letter-spacing:.18em;text-transform:uppercase;
  color:var(--white);margin-bottom:9px}
.whyus p{font-size:13.5px;line-height:1.65;color:#8f919a}

/* ---------------- job detail ---------------- */
.jhero{position:relative;padding:150px 0 0;overflow:hidden}
.jh-back{display:inline-flex;align-items:center;gap:9px;font-family:var(--data);font-weight:700;font-size:12px;
  letter-spacing:.24em;text-transform:uppercase;color:var(--steel-mid);transition:color .25s,gap .25s;margin-bottom:28px;
  border:1px solid #2d2d2d;border-radius:var(--rd-xs);padding:9px 15px;background:linear-gradient(178deg,#161616,#101010)}
.jh-back:hover{color:#fff;border-color:var(--red-hot);gap:14px}
.jh-h1{font-family:var(--nulshock);font-size:clamp(26px,4.3vw,52px);text-transform:uppercase;line-height:1.1;
  text-wrap:balance;margin-top:20px;
  background:linear-gradient(178deg,#fff 8%,#c9ccd4 34%,#787b85 52%,#e2e4ea 64%,#84878f 90%);
  -webkit-background-clip:text;background-clip:text;-webkit-text-fill-color:transparent}
.jh-sum{margin-top:20px;font-size:17px;line-height:1.7;color:#a9abb4;max-width:760px}
.jh-cta{margin-top:34px;display:flex;gap:14px;flex-wrap:wrap;align-items:center}

/* sticky apply bar */
.stickybar{position:fixed;left:0;right:0;bottom:0;z-index:180;transform:translateY(110%);
  transition:transform .35s cubic-bezier(.2,.7,.2,1);
  background:rgba(8,8,8,.93);backdrop-filter:blur(16px);-webkit-backdrop-filter:blur(16px);
  border-top:1px solid rgba(168,16,30,.42);padding:13px 0}
.stickybar.show{transform:translateY(0)}
.sb-in{display:flex;align-items:center;justify-content:space-between;gap:22px}
.sb-t{min-width:0}
.sb-t b{display:block;font-family:var(--nulshock);font-size:14px;text-transform:uppercase;color:var(--white);
  white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.sb-t span{display:block;font-family:var(--data);font-weight:600;font-size:11.5px;letter-spacing:.18em;
  text-transform:uppercase;color:var(--steel-low);margin-top:3px}
.sb-in .btn{flex-shrink:0}

.jbody{display:grid;grid-template-columns:1.6fr .9fr;gap:56px;align-items:start}
.jb-main > * + *{margin-top:56px}
.jb-h{display:flex;align-items:center;gap:15px;margin-bottom:24px}
.jb-h .num{flex-shrink:0;font-family:var(--nulshock);font-size:12px;color:var(--red-hot);
  border:1px solid rgba(168,16,30,.4);border-radius:var(--rd-xs);padding:7px 10px;line-height:1}
.jb-h h2{font-family:var(--data);font-weight:700;font-size:14px;letter-spacing:.3em;text-transform:uppercase;
  color:var(--white);white-space:nowrap}
.jb-h::after{content:'';flex:1;height:1px;background:var(--hairline)}
.jb-lede{font-size:16px;line-height:1.75;color:#a9abb4}

/* responsibilities as numbered cards */
.rcards{display:grid;gap:14px}
.rcard{display:flex;gap:20px;align-items:flex-start;background:linear-gradient(178deg,#141414,#0e0e0e);
  border:1px solid #242424;border-radius:var(--rd-sm);padding:24px 26px;transition:.3s;position:relative;overflow:hidden}
.rcard::after{content:'';position:absolute;left:0;top:0;bottom:0;width:2px;background:var(--red-hot);
  transform:scaleY(0);transform-origin:top;transition:transform .4s}
.rcard:hover{border-color:#3c3c3c;transform:translateX(4px)}
.rcard:hover::after{transform:scaleY(1)}
.rcard .rn{flex-shrink:0;font-family:var(--nulshock);font-size:15px;color:var(--steel-low);
  min-width:26px;line-height:1.5;transition:color .3s}
.rcard:hover .rn{color:var(--red-hot)}
.rcard .rt{font-family:var(--data);font-weight:700;font-size:14px;letter-spacing:.16em;text-transform:uppercase;
  color:var(--white);margin-bottom:7px}
.rcard .rd{font-size:14.5px;line-height:1.65;color:#8f919a}

/* requirements: two columns of ticked items */
.reqs{display:grid;grid-template-columns:1fr 1fr;gap:20px}
.reqcol{border:1px solid var(--hairline);background:var(--coal);border-radius:var(--rd-sm);padding:28px 26px}
.reqcol > h4{font-family:var(--data);font-weight:700;font-size:12px;letter-spacing:.26em;text-transform:uppercase;
  padding-bottom:13px;margin-bottom:6px;border-bottom:2px solid var(--red);
  display:flex;align-items:center;justify-content:space-between;gap:12px}
.reqcol > h4 span{color:var(--white)}
.reqcol > h4 em{font-style:normal;font-family:var(--nulshock);font-size:11px;color:var(--steel-low)}
.reqcol.nice > h4{border-bottom-color:#2d2d2d}
.reqcol ul li{display:flex;gap:13px;align-items:flex-start;padding:11px 0;border-bottom:1px solid #1a1a1a;
  font-size:14.2px;line-height:1.6;color:#9b9da6}
.reqcol ul li:last-child{border-bottom:0}
.reqcol ul li svg{flex-shrink:0;margin-top:4px}

/* benefits as icon cards */
.bgrid{display:grid;grid-template-columns:1fr 1fr;gap:16px}
.bcard{background:linear-gradient(178deg,#121212,#0c0c0c);border:1px solid #252525;border-radius:var(--rd-sm);
  padding:26px 24px;display:flex;gap:18px;align-items:flex-start;transition:transform .3s,border-color .3s}
.bcard:hover{transform:translateY(-4px);border-color:#3c3c3c}
.bic{width:44px;height:44px;flex-shrink:0;border:1px solid #2d2d2d;border-radius:var(--rd-xs);
  background:linear-gradient(178deg,#1e1e1e,#141414);display:flex;align-items:center;justify-content:center;transition:.3s}
.bcard:hover .bic{border-color:var(--red-hot);box-shadow:0 0 20px rgba(168,16,30,.24)}
.bcard h4{font-family:var(--data);font-weight:700;font-size:13px;letter-spacing:.18em;text-transform:uppercase;
  color:var(--white);margin-bottom:7px}
.bcard p{font-size:13.8px;line-height:1.62;color:#8f919a}

/* right rail */
.jrail{position:sticky;top:104px;display:flex;flex-direction:column;gap:18px}
.rail{border:1px solid var(--hairline);background:linear-gradient(178deg,var(--plate2),var(--plate));
  border-radius:var(--rd);padding:28px 26px;position:relative;overflow:hidden}
.rail::before{content:'';position:absolute;top:0;left:0;right:0;height:2px;
  background:linear-gradient(90deg,var(--red-hot),transparent)}
.rail h4{font-family:var(--data);font-weight:700;font-size:12.5px;letter-spacing:.28em;text-transform:uppercase;
  color:var(--white);margin-bottom:18px}
.rrow{display:flex;justify-content:space-between;align-items:baseline;gap:16px;padding:11px 0;
  border-bottom:1px solid #1a1a1a;font-family:var(--data)}
.rrow:last-of-type{border-bottom:0}
.rrow .k{font-weight:600;font-size:11.5px;letter-spacing:.2em;text-transform:uppercase;color:var(--steel-low)}
.rrow .v{font-weight:700;font-size:13.5px;letter-spacing:.05em;color:var(--white);text-align:right}
.rrow .v.red{color:var(--ember)}
.rail .btn{width:100%;justify-content:center;margin-top:20px}
.wline{display:flex;gap:14px;align-items:flex-start;font-size:14px;line-height:1.6;color:#9b9da6;margin-bottom:13px}
.wline:last-child{margin-bottom:0}
.wline svg{flex-shrink:0;margin-top:4px}
.wline b{color:var(--white);font-weight:600}
.wline a{color:var(--steel-hi);transition:color .25s}
.wline a:hover{color:var(--ember)}

/* apply */
.fshell{margin-top:36px;border:1px solid var(--hairline);border-radius:var(--rd);overflow:hidden;
  position:relative;background:#0c0c0c}
.fshell::before{content:'';position:absolute;top:0;left:0;right:0;height:2px;z-index:2;pointer-events:none;
  background:linear-gradient(90deg,transparent,var(--red-hot),transparent)}
/* the iframe carries the form's own background and padding. do not override either. */
.fshell iframe{display:block;width:100%;border:0;min-height:920px;color-scheme:normal}
.fshell.plain{background:transparent}
.fnote{font-family:var(--data);font-weight:600;font-size:13.5px;letter-spacing:.06em;color:var(--steel-low);margin-top:18px}
.fnote a{color:var(--steel-hi)}
.fnote a:hover{color:var(--ember)}
.ffallback{padding:52px 36px;text-align:center}
.ffallback p{font-size:15px;line-height:1.7;color:var(--steel-mid);margin-bottom:22px;max-width:520px;
  margin-left:auto;margin-right:auto}

/* ---------------- responsive ---------------- */
@media (max-width:1080px){
  .jbody{grid-template-columns:1fr;gap:46px}
  .jrail{position:static;display:grid;grid-template-columns:1fr 1fr;gap:18px}
  .cband-in{grid-template-columns:1fr;gap:34px;padding:44px 38px}
  .mtiles{grid-template-columns:1fr 1fr}
  .mtile:nth-child(2n){border-right:0}
  .mtile:nth-child(-n+2){border-bottom:1px solid var(--hairline)}
  .whyus{grid-template-columns:1fr 1fr}
}
@media (max-width:860px){
  .jgrid{grid-template-columns:1fr}
  .reqs,.bgrid{grid-template-columns:1fr}
  .jrail{grid-template-columns:1fr}
}
@media (max-width:720px){
  .careers-hero{padding:128px 0 56px}
  .jhero{padding:122px 0 0}
  .cband-in{padding:34px 24px;border-radius:var(--rd-sm)}
  .cb-h{font-size:clamp(20px,5.8vw,27px)}
  .cb-p{font-size:14.5px}
  .cb-foot{gap:13px}
  .cb-foot .cb-band-btn{flex:1 1 100%;justify-content:center}
  .ch-h1{font-size:clamp(25px,7.2vw,37px)}
  .jh-h1{font-size:clamp(23px,6.4vw,32px)}
  .jh-sum{font-size:15.5px}
  .ch-cta .btn,.jh-cta .btn{flex:1 1 100%;justify-content:center}
  .jcard{padding:28px 23px 24px}
  .rcard{padding:21px 20px;gap:15px}
  .rail{padding:24px 21px}
  .mtiles{margin-top:28px}
  .mtile{padding:20px 17px}
  .mtile .v{font-size:14px}
  .fshell iframe{min-height:1040px}
  .jb-h h2{font-size:12.5px;letter-spacing:.22em;white-space:normal}
  .sb-t span{display:none}
  .stickybar{padding:11px 0}
}
@media (max-width:480px){
  .jf{padding:10px 14px;font-size:11.5px;letter-spacing:.14em}
  .mtiles{grid-template-columns:1fr}
  .mtile{border-right:0;border-bottom:1px solid var(--hairline)}
  .mtile:last-child{border-bottom:0}
  .bcard{padding:21px 18px;gap:14px}
  .reqcol{padding:23px 20px}
  .sb-in{gap:14px}
  .sb-t b{font-size:12.5px}
}
@media (prefers-reduced-motion:reduce){
  .cb-dot,.jc-go{animation:none}
  .stickybar{transition:none}
}
`;
write('careers.css', CAREERS_CSS);

/* ---------------- icon set ---------------- */
const ic = {
  pin:   (c='#a8101e') => `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="${c}" stroke-width="2.2"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"/><circle cx="12" cy="10" r="3"/></svg>`,
  bld:   (c='#a8101e') => `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="${c}" stroke-width="2.2"><path d="M3 21h18M5 21V7l7-4 7 4v14M10 10h4M10 14h4M10 18h4"/></svg>`,
  pay:   (c='#f04f33') => `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="${c}" stroke-width="2.2"><path d="M6 3h12M6 8h12M9 13h6a4 4 0 0 0 0-8M6 13h3l6 8"/></svg>`,
  clk:   (c='#a8101e') => `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="${c}" stroke-width="2.2"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg>`,
  cal:   (c='#a8101e') => `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="${c}" stroke-width="2.2"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M3 10h18M8 3v4M16 3v4"/></svg>`,
  brief: (c='#a8101e') => `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="${c}" stroke-width="2.2"><rect x="2" y="7" width="20" height="14" rx="2"/><path d="M8 7V5a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2M2 13h20"/></svg>`,
  tick:  (c='#f04f33') => `<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="${c}" stroke-width="2.6"><path d="M20 6 9 17l-5-5"/></svg>`,
  plus:  (c='#5f5f5f') => `<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="${c}" stroke-width="2.6"><path d="M12 5v14M5 12h14"/></svg>`,
  star:  (c='#a8101e') => `<svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="${c}" stroke-width="2"><path d="m12 3 2.6 5.8 6.4.7-4.8 4.3 1.3 6.2L12 17l-5.5 3 1.3-6.2L3 9.5l6.4-.7z"/></svg>`,
  phone: (c='#a8101e') => `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="${c}" stroke-width="2.2"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.13.96.36 1.9.7 2.81a2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45c.91.34 1.85.57 2.81.7A2 2 0 0 1 22 16.92z"/></svg>`
};

const mono   = (c, lg) => `<span class="mono${lg ? ' lg' : ''}"><b>${c}</b><i>${companies[c].name}</i></span>`;
const EMB = Object.assign(
  { hideTitle: true, transparentBackground: false, alignLeft: false, dynamicHeight: true },
  config.tallyEmbed || {});
const tally = (id, p) => {
  const q = new URLSearchParams(p);
  if (EMB.hideTitle)             q.set('hideTitle', '1');
  if (EMB.transparentBackground) q.set('transparentBackground', '1');
  if (EMB.alignLeft)             q.set('alignLeft', '1');
  if (EMB.dynamicHeight)         q.set('dynamicHeight', '1');
  return `https://tally.so/embed/${id}?${q}`;
};
const TALLY_JS = '<script async src="https://tally.so/widgets/embed.js"></script>';
const hasForm = id => id && !/REPLACE/i.test(id);

/* ---------------- the band ---------------- */
function buildBand(scope) {
  const pool = scope ? JOBS.filter(j => j.company === scope) : JOBS;
  const n = pool.length;

  if (!n) {
    const who = scope ? companies[scope].name : 'the group';
    return `<section class="cband">
  <div class="wrap">
    <div class="cband-in empty">
      <div class="cb-l">
        <div class="cb-eyebrow">Careers</div>
        <h2 class="cb-h">No Open Roles <em>Right Now.</em></h2>
        <p class="cb-p">We are not hiring at ${esc(who)} at this moment, but we still want to hear from good people. Send us your CV and we will come back to you the moment something opens that fits what you do.</p>
        <div class="cb-foot">
          <a class="btn btn-red" href="/careers#general">Send Us Your CV</a>
          <a class="btn btn-steel" href="/careers">See All Openings</a>
        </div>
      </div>
    </div>
  </div>
</section>`;
  }

  const roles = pool.slice(0, 3).map(j => `        <a class="cb-role" href="${jobUrl(j)}">
          <span class="m">${j.company}</span>
          <span class="tx"><b>${esc(j.title)}</b><i>${esc(co(j).shortLocation)} &middot; ${esc(j.workplace)}</i></span>
          <span class="go">&rarr;</span>
        </a>`).join('\n');

  const more = pool.length > 3
    ? `\n        <a class="cb-all" href="/careers">View all ${pool.length} openings &rarr;</a>` : '';

  const head = scope
    ? `We&rsquo;re Hiring At <em>${esc(companies[scope].name)}.</em>`
    : `Build What India&rsquo;s <em>Industry Runs On.</em>`;
  const copy = scope
    ? `Join the team at ${esc(companies[scope].shortLocation)} and work on components that keep the country&rsquo;s biggest plants running.`
    : `Forty years in, still growing. Heavy engineering, real machines, work that ships to the largest plants in the country.`;

  return `<section class="cband">
  <div class="wrap">
    <div class="cband-in">
      <div class="cb-l">
        <div class="cb-eyebrow">Careers</div>
        <h2 class="cb-h">${head}</h2>
        <p class="cb-p">${copy}</p>
        <div class="cb-foot">
          <span class="cb-live"><span class="cb-dot"></span>${n} open ${n === 1 ? 'role' : 'roles'}</span>
          <a class="cb-band-btn" href="/careers">Join Us</a>
        </div>
      </div>
      <div class="cb-r">
${roles}${more}
      </div>
    </div>
  </div>
</section>`;
}

/* ---------------- host pages ---------------- */
console.log('\nUpdating host pages...');
HOST_PAGES.forEach(p => {
  if (!exists(p.file)) { console.log('  skip ' + p.file + ' (not found)'); return; }
  let html = read(p.file);

  html = inject(html, 'CAREERS-CSS', '<link rel="stylesheet" href="/careers.css">',
    (h, x) => h.replace('</head>', x + '\n</head>'));

  /* nav: only if explicitly enabled in config. default OFF, the bar is full. */
  if (NAV_LINK) {
    html = inject(html, 'CAREERS-NAV', '      <a href="/careers">Careers</a>', (h, x) => {
      const re = /(<a href="\/?#contact">Contact<\/a>\s*)/;
      return re.test(h) ? h.replace(re, '$1\n' + x + '\n') : h;
    });
  } else {
    html = html.replace(/<!-- CAREERS-NAV:START -->[\s\S]*?<!-- CAREERS-NAV:END -->\n?/g, '');
  }

  html = inject(html, 'CAREERS-FOOT', '          <a href="/careers">Careers</a>', (h, x) => {
    const re = /(<a href="\/?#infrastructure">Infrastructure<\/a>\s*)(?=<\/div>)/;
    return re.test(h) ? h.replace(re, '$1\n' + x + '\n        ') : h;
  });

  /* retire the dead Google Form links */
  html = html.replace(/<a([^>]*?)href="https:\/\/forms\.gle\/[A-Za-z0-9]+"([^>]*?)>/g,
    (m, a, b) => `<a${a}href="/careers"${b.replace(/\s*target="_blank"/, '').replace(/\s*rel="noopener"/, '')}>`);

  html = inject(html, 'CAREERS-BAND', buildBand(p.company), (h, x) => {
    if (/<section class="next-nav"/.test(h)) return h.replace(/(<section class="next-nav")/, x + '\n\n$1');
    return h.replace(/(<footer>)/, x + '\n\n$1');
  });

  write(p.file, html);
});

/* ---------------- page shell ---------------- */
const shell = (o) => `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${o.title}</title>
<meta name="description" content="${o.desc}">
${o.keywords ? `<meta name="keywords" content="${o.keywords}">\n` : ''}<link rel="canonical" href="${o.url}">
<meta property="og:title" content="${o.ogTitle}">
<meta property="og:description" content="${o.desc}">
<meta property="og:url" content="${o.url}">
<meta property="og:type" content="website">
<meta property="og:image" content="https://raw.githubusercontent.com/shauryamanglik/Ferrous/main/Ferrous%20Logos/Ferrous%20Circle.png">
<meta name="twitter:card" content="summary">
<link rel="icon" href="https://raw.githubusercontent.com/shauryamanglik/Ferrous/main/Ferrous%20Logos/Ferrous%20Circle.png">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
${fontLinks}
${o.ld || ''}${analytics}
${styleBlock}
<link rel="stylesheet" href="/careers.css">
</head>
<body>
<div id="progress"></div>
<div id="cursor"></div><div id="cursor-ring"></div>
<div class="orbs"><div class="orb r" style="width:480px;height:480px;top:-160px;right:-120px"></div><div class="orb s" style="width:420px;height:420px;bottom:-140px;left:-120px;animation-delay:-12s"></div></div>

${navForSub}

${o.body}

${footForSub}

${scriptBlock}

${o.scripts || ''}
</body>
</html>
`;

const nextNav = (here) => {
  const items = [
    { h: '/',      k: 'The Group',       t: 'Ferrous Group',       d: '40+ years of engineering excellence. Three companies, one standard.' },
    { h: '/fe',    k: 'Cement &amp; Steel', t: 'Ferrous Engineering', d: 'Heavy fabrication, precision machining &amp; the RAL specialists.' },
    { h: '/de',    k: 'Power &amp; Defence', t: 'Deepak Engineering',  d: 'Critical spares: built new, developed &amp; restored beyond new.' },
    { h: '/fapl',  k: 'Automation',      t: 'Ferrous Automations', d: 'Telescopic belt conveyors &amp; material handling automation.' }
  ];
  return `<section class="next-nav" aria-label="Explore the Ferrous Group">
  <div class="wrap">
    <div class="eyebrow rv"><span class="idx">&raquo;</span> Keep Exploring</div>
    <h2 class="steel rv">Where To <span class="red-word">Next?</span></h2>
    <div class="nn-grid">
${items.map((x, i) => `      <a class="nn rv${i ? ' rv-d' + i : ''}" href="${x.h}"><span class="nn-k">${x.k}</span><span class="nn-t">${x.t}</span><span class="nn-d">${x.d}</span><span class="nn-a">Visit Page &rarr;</span></a>`).join('\n')}
    </div>
  </div>
</section>`;
};

/* ---------------- careers index ---------------- */
console.log('\nGenerating careers page...');

const cosInPlay = [...new Set(JOBS.map(j => j.company))];

const filters = JOBS.length > 1 && cosInPlay.length > 1 ? `    <div class="jfilters rv rv-d1" role="tablist" aria-label="Filter by company">
      <button class="jf on" data-f="all" role="tab" aria-selected="true">All Roles <em>${JOBS.length}</em></button>
${cosInPlay.map(c => `      <button class="jf" data-f="${c}" role="tab" aria-selected="false">${esc(companies[c].name)} <em>${JOBS.filter(j => j.company === c).length}</em></button>`).join('\n')}
    </div>\n` : '';

const cards = JOBS.map((j, i) => {
  const pay = salaryText(j);
  return `      <article class="jcard rv${i % 3 ? ' rv-d' + (i % 3) : ''}" data-co="${j.company}" data-href="${jobUrl(j)}" tabindex="0" role="link" aria-label="${esc(j.title)} at ${esc(co(j).name)}">
        <div class="glow"></div>
        <div class="jc-head">${mono(j.company)}${j.experience ? `<span class="jc-exp">${esc(j.experience)}</span>` : ''}</div>
        <h3 class="jc-title">${esc(j.title)}</h3>
        <p class="jc-sum">${j.summary}</p>
        <div class="jc-spec">
          <div class="jc-row"><span class="k">Location</span><span class="v">${esc(co(j).shortLocation)}</span></div>
          <div class="jc-row"><span class="k">Workplace</span><span class="v">${esc(j.workplace)} &middot; ${esc(typeLabel(j.employmentType))}</span></div>${pay ? `
          <div class="jc-row"><span class="k">Salary</span><span class="v red">${pay}</span></div>` : ''}
        </div>
        <span class="jc-go">View Role &amp; Apply</span>
      </article>`;
}).join('\n');

const openings = JOBS.length
  ? `${filters}    <div class="jgrid" id="jgrid">\n${cards}\n    </div>
    <div class="jempty" id="nomatch" style="display:none">
      <h3>Nothing open here right now</h3>
      <p>Try another filter, or send us your CV below and we will reach out when a matching role opens.</p>
    </div>`
  : `    <div class="jempty rv">
      <h3>No open roles right now</h3>
      <p>We are not actively hiring at the moment. Send us your CV below. We keep strong profiles on file and get in touch the moment something relevant opens up.</p>
    </div>`;

const genForm = hasForm(config.generalTallyFormId)
  ? `    <div class="fshell rv">
      <iframe src="${tally(config.generalTallyFormId, { source: 'careers-general' })}" loading="lazy" title="General application" style="min-height:800px"></iframe>
    </div>`
  : `    <div class="fshell rv"><div class="ffallback">
      <p>Our general application form is being set up. Until it is live, email your CV directly and it lands in the same inbox.</p>
      <a class="btn btn-red" href="mailto:${config.careersEmail}?subject=General%20Application">Email Your CV</a>
    </div></div>`;

const careersBody = `<header class="careers-hero">
  <div class="wrap">
    <div class="eyebrow rv"><span class="idx">&raquo;</span> Careers</div>
    <h1 class="ch-h1 rv">Build What India&rsquo;s <br>Industry <span class="red-word">Runs On.</span></h1>
    <p class="lede rv rv-d1" style="margin-top:22px">Forty years of heavy engineering out of Central India. We manufacture and restore the critical components inside the country&rsquo;s largest power, cement, steel and defence plants. If you want work with real weight behind it, this is the place.</p>
    <div class="mtiles rv rv-d2">
      <div class="mtile accent"><div class="k">${ic.brief('#f04f33')} Open Roles</div><div class="v red">${JOBS.length} ${JOBS.length === 1 ? 'position' : 'positions'}</div></div>
      <div class="mtile"><div class="k">${ic.bld()} Companies</div><div class="v">Three</div></div>
      <div class="mtile"><div class="k">${ic.pin()} Locations</div><div class="v">Chandrapur &amp; Pune</div></div>
      <div class="mtile"><div class="k">${ic.clk()} Established</div><div class="v">1985</div></div>
    </div>
    <div class="ch-cta rv rv-d3">
      <a class="btn btn-red" href="#openings">See Open Roles</a>
      <a class="btn btn-steel" href="#general">Send Us Your CV</a>
    </div>
  </div>
</header>

<div class="seam"><div class="burn"></div><div class="torch"></div></div>

<section id="openings">
  <div class="wrap">
    <div class="eyebrow rv"><span class="idx">01</span> Open Positions</div>
    <h2 class="steel rv">Where You <span class="red-word">Fit In.</span></h2>
    <p class="lede rv rv-d1" style="margin-bottom:34px">Every role below is live right now. Apply online in one form, or walk in to the plant and talk to us directly.</p>
${openings}
  </div>
</section>

<div class="seam"><div class="burn"></div><div class="torch"></div></div>

<section id="why">
  <div class="wrap">
    <div class="eyebrow rv"><span class="idx">02</span> Why Ferrous</div>
    <h2 class="steel rv">What You Get <br>Working <span class="red-word">Here.</span></h2>
    <div class="whyus">
      <div class="w rv"><span class="n">01</span><h3>Machines That Matter</h3><p>A 3.5 m vertical lathe, a 3 &times; 13 m CNC plasma bed, a 500 MT press. Equipment most workshops in India will never touch.</p></div>
      <div class="w rv rv-d1"><span class="n">02</span><h3>Work You Can Point At</h3><p>Components running inside NTPC, Ultratech, SAIL and Ordnance Factory plants. Real output, not slide decks.</p></div>
      <div class="w rv rv-d2"><span class="n">03</span><h3>A Small Team, Real Ownership</h3><p>You will not be a row in a spreadsheet. Your work is visible, and so is the difference you make to it.</p></div>
      <div class="w rv rv-d3"><span class="n">04</span><h3>Forty Years Of Stability</h3><p>Founded 1985, three companies, 2,00,000+ sq. ft. and clients who have come back for decades.</p></div>
    </div>
  </div>
</section>

<div class="seam"><div class="burn"></div><div class="torch"></div></div>

<section id="general">
  <div class="wrap">
    <div class="eyebrow rv"><span class="idx">03</span> General Application</div>
    <h2 class="steel rv">Nothing Fits? <br>Send It <span class="red-word">Anyway.</span></h2>
    <p class="lede rv rv-d1">We keep strong profiles on file. If none of the roles above match what you do, tell us what you are good at and we will reach out when something opens.</p>
${genForm}
    <p class="fnote rv">Form not loading? Email your CV to <a href="mailto:${config.careersEmail}">${config.careersEmail}</a>.</p>
  </div>
</section>

<div class="seam"><div class="burn"></div><div class="torch"></div></div>

${nextNav('/careers')}`;

write('careers/index.html', shell({
  title: `Careers | Ferrous Group | Heavy Engineering Jobs in Chandrapur &amp; Pune`,
  ogTitle: 'Careers | Ferrous Group',
  desc: `${JOBS.length} open ${JOBS.length === 1 ? 'role' : 'roles'} at Ferrous Group. Heavy engineering, fabrication, commercial and automation jobs at Tadali MIDC Chandrapur and MIDC Chakan Pune. Apply online or walk in.`,
  keywords: 'jobs in Chandrapur, heavy engineering jobs Maharashtra, Tadali MIDC jobs, Ferrous Group careers, workshop supervisor job Chandrapur, sales engineer job Chandrapur, e-tendering job India',
  url: SITE + '/careers',
  body: careersBody,
  scripts: `<script>
(function(){
  var grid=document.getElementById('jgrid'); if(!grid)return;
  var cards=[].slice.call(grid.querySelectorAll('.jcard')), nm=document.getElementById('nomatch');
  var fine=matchMedia('(pointer:fine)').matches, calm=matchMedia('(prefers-reduced-motion: reduce)').matches;
  cards.forEach(function(c){
    var go=function(){location.href=c.dataset.href};
    c.addEventListener('click',go);
    c.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();go()}});
    if(fine&&!calm){
      var glow=c.querySelector('.glow');
      c.addEventListener('pointermove',function(e){
        var r=c.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;
        c.style.transform='perspective(1100px) rotateX('+(((y/r.height)-.5)*-6)+'deg) rotateY('+(((x/r.width)-.5)*8)+'deg) translateY(-5px)';
        if(glow){glow.style.left=x+'px';glow.style.top=y+'px'}
      });
      c.addEventListener('pointerleave',function(){c.style.transform=''});
    }
  });
  document.querySelectorAll('.jf').forEach(function(b){
    b.addEventListener('click',function(){
      var f=b.dataset.f,shown=0;
      document.querySelectorAll('.jf').forEach(function(x){
        var on=x===b;x.classList.toggle('on',on);x.setAttribute('aria-selected',on?'true':'false');
      });
      cards.forEach(function(c){
        var s=(f==='all'||c.dataset.co===f);c.classList.toggle('hide',!s);if(s)shown++;
      });
      if(nm)nm.style.display=shown?'none':'';
    });
  });
})();
</script>
${hasForm(config.generalTallyFormId) ? TALLY_JS : ''}`
}));

/* ---------------- job pages ---------------- */
console.log('\nGenerating job pages...');

function jobPage(j) {
  const c = co(j), pay = salaryText(j);

  const ld = {
    '@context': 'https://schema.org', '@type': 'JobPosting',
    title: plain(j.title),
    description: '<p>' + plain(j.about) + '</p>'
      + '<h3>Key Responsibilities</h3><ul>' + j.responsibilities.map(r => `<li><strong>${plain(r.t)}:</strong> ${plain(r.d)}</li>`).join('') + '</ul>'
      + '<h3>What We Are Looking For</h3><ul>' + j.mustHave.map(r => `<li>${plain(r)}</li>`).join('') + '</ul>'
      + (j.niceToHave?.length ? '<h3>Nice To Have</h3><ul>' + j.niceToHave.map(r => `<li>${plain(r)}</li>`).join('') + '</ul>' : '')
      + (j.benefits?.length ? '<h3>Benefits</h3><ul>' + j.benefits.map(b => `<li><strong>${plain(b.t)}:</strong> ${plain(b.d)}</li>`).join('') + '</ul>' : ''),
    identifier: { '@type': 'PropertyValue', name: 'Ferrous Group', value: j.slug },
    datePosted: j.posted,
    employmentType: j.employmentType || 'FULL_TIME',
    hiringOrganization: { '@type': 'Organization', name: c.name, sameAs: SITE + c.path,
      logo: 'https://raw.githubusercontent.com/shauryamanglik/Ferrous/main/Ferrous%20Logos/Ferrous%20Circle.png' },
    jobLocation: { '@type': 'Place', address: { '@type': 'PostalAddress',
      streetAddress: c.streetAddress, addressLocality: c.locality, addressRegion: c.region,
      postalCode: c.postalCode, addressCountry: 'IN' } },
    directApply: true
  };
  /* Google has no "hybrid". Hybrid stays a located job; only true remote is TELECOMMUTE. */
  if (String(j.workplace).toLowerCase() === 'remote') {
    ld.jobLocationType = 'TELECOMMUTE';
    ld.applicantLocationRequirements = { '@type': 'Country', name: 'India' };
  }
  if (j.salary?.min != null) ld.baseSalary = { '@type': 'MonetaryAmount', currency: 'INR',
    value: { '@type': 'QuantitativeValue', minValue: j.salary.min,
             maxValue: j.salary.max ?? j.salary.min, unitText: j.salary.unit || 'MONTH' } };
  if (j.validThrough) ld.validThrough = j.validThrough;

  const form = hasForm(config.tallyFormId)
    ? `    <div class="fshell rv">
      <iframe src="${tally(config.tallyFormId, { role: plain(j.title), role_slug: j.slug, company: c.name })}" loading="lazy" title="Application form for ${esc(j.title)}"></iframe>
    </div>`
    : `    <div class="fshell rv"><div class="ffallback">
      <p>Our online form is being set up. Until it is live, email your CV with the role name in the subject and it reaches the same desk.</p>
      <a class="btn btn-red" href="mailto:${config.careersEmail}?subject=Application%3A%20${encodeURIComponent(plain(j.title))}">Email Your CV</a>
    </div></div>`;

  const others = JOBS.filter(x => x.slug !== j.slug).slice(0, 2);

  const body = `<header class="jhero">
  <div class="wrap">
    <a class="jh-back rv" href="/careers">&larr; All Openings</a>
    <div class="rv">${mono(j.company, true)}</div>
    <h1 class="jh-h1 rv">${esc(j.title)}</h1>
    <p class="jh-sum rv rv-d1">${j.summary}</p>
    <div class="mtiles rv rv-d2">
      <div class="mtile"><div class="k">${ic.pin()} Location</div><div class="v">${esc(c.shortLocation)}</div></div>
      <div class="mtile"><div class="k">${ic.bld()} Workplace</div><div class="v">${esc(j.workplace)}</div></div>
      <div class="mtile"><div class="k">${ic.brief()} Experience</div><div class="v">${esc(j.experience || typeLabel(j.employmentType))}</div></div>
      ${pay ? `<div class="mtile accent"><div class="k">${ic.pay()} Salary</div><div class="v red">${pay}</div></div>`
            : `<div class="mtile"><div class="k">${ic.clk()} Type</div><div class="v">${esc(typeLabel(j.employmentType))}</div></div>`}
    </div>
    <div class="jh-cta rv rv-d3">
      <a class="btn btn-red" href="#apply">Apply For This Role</a>
      ${j.walkIn ? `<a class="btn btn-steel" href="#walk-in">Walk-In Details</a>` : ''}
    </div>
  </div>
</header>

<div class="seam" style="margin-top:72px"><div class="burn"></div><div class="torch"></div></div>

<section>
  <div class="wrap">
    <div class="jbody">
      <div class="jb-main">

        <div class="rv">
          <div class="jb-h"><span class="num">01</span><h2>About The Role</h2></div>
          <p class="jb-lede">${j.about}</p>
        </div>

        <div class="rv">
          <div class="jb-h"><span class="num">02</span><h2>What You&rsquo;ll Do</h2></div>
          <div class="rcards">
${j.responsibilities.map((r, i) => `            <div class="rcard"><span class="rn">${String(i + 1).padStart(2, '0')}</span><div><div class="rt">${r.t}</div><div class="rd">${r.d}</div></div></div>`).join('\n')}
          </div>
        </div>

        <div class="rv">
          <div class="jb-h"><span class="num">03</span><h2>What We&rsquo;re Looking For</h2></div>
          <div class="reqs">
            <div class="reqcol">
              <h4><span>Must Have</span><em>${j.mustHave.length}</em></h4>
              <ul>
${j.mustHave.map(r => `                <li>${ic.tick()}<span>${r}</span></li>`).join('\n')}
              </ul>
            </div>${j.niceToHave?.length ? `
            <div class="reqcol nice">
              <h4><span>Nice To Have</span><em>${j.niceToHave.length}</em></h4>
              <ul>
${j.niceToHave.map(r => `                <li>${ic.plus()}<span>${r}</span></li>`).join('\n')}
              </ul>
            </div>` : ''}
          </div>
        </div>
${j.benefits?.length ? `
        <div class="rv">
          <div class="jb-h"><span class="num">04</span><h2>Perks &amp; Benefits</h2></div>
          <div class="bgrid">
${j.benefits.map(b => `            <div class="bcard"><span class="bic">${ic.star()}</span><div><h4>${b.t}</h4><p>${b.d}</p></div></div>`).join('\n')}
          </div>
        </div>` : ''}
      </div>

      <aside class="jrail">
        <div class="rail rv">
          <h4>Role Snapshot</h4>
          <div class="rrow"><span class="k">Company</span><span class="v">${esc(c.name)}</span></div>
          <div class="rrow"><span class="k">Sector</span><span class="v">${c.sector}</span></div>
          <div class="rrow"><span class="k">Location</span><span class="v">${esc(c.shortLocation)}</span></div>
          <div class="rrow"><span class="k">Workplace</span><span class="v">${esc(j.workplace)}</span></div>
          <div class="rrow"><span class="k">Type</span><span class="v">${esc(typeLabel(j.employmentType))}</span></div>${j.experience ? `
          <div class="rrow"><span class="k">Experience</span><span class="v">${esc(j.experience)}</span></div>` : ''}${pay ? `
          <div class="rrow"><span class="k">Salary</span><span class="v red">${pay}</span></div>` : ''}
          <a class="btn btn-red" href="#apply">Apply Now</a>
        </div>
${j.walkIn ? `        <div class="rail rv rv-d1">
          <h4>Prefer To Walk In?</h4>
          <div class="wline">${ic.pin()}<span><b>${esc(c.name)}</b><br>${esc(c.streetAddress)}, ${esc(c.locality)}, ${esc(c.region)} ${esc(c.postalCode)}</span></div>
          <div class="wline">${ic.cal()}<span>${esc(config.walkIn.days)}</span></div>
          <div class="wline">${ic.clk()}<span>${esc(config.walkIn.time)}</span></div>
          <div class="wline">${ic.phone()}<a href="tel:${c.phone}">${esc(c.phoneDisplay)}</a></div>
          <div class="wline">${ic.brief()}<span>Bring a printed CV and any certificates.</span></div>
        </div>` : ''}
      </aside>
    </div>
  </div>
</section>

<div class="seam"><div class="burn"></div><div class="torch"></div></div>

<section id="apply">
  <div class="wrap">
    <div class="eyebrow rv"><span class="idx">&raquo;</span> Apply</div>
    <h2 class="steel rv">Apply For <br>This <span class="red-word">Role.</span></h2>
    <p class="lede rv rv-d1">One form, and it arrives already tagged to ${esc(j.title)}. Freshers are welcome. If you have not worked yet, the form asks about your projects and training instead.</p>
${form}
    <p class="fnote rv">Form not loading? Email your CV to <a href="mailto:${config.careersEmail}?subject=Application%3A%20${encodeURIComponent(plain(j.title))}">${config.careersEmail}</a> with the role name in the subject.</p>
  </div>
</section>
${j.walkIn ? `
<div class="seam"><div class="burn"></div><div class="torch"></div></div>

<section id="walk-in">
  <div class="wrap">
    <div class="eyebrow rv"><span class="idx">&raquo;</span> Walk-In</div>
    <h2 class="steel rv">Or Just <span class="red-word">Turn Up.</span></h2>
    <p class="lede rv rv-d1">We interview walk-in candidates at the plant. No appointment needed. Bring a printed CV and any certificates you have.</p>
    <div class="mtiles rv rv-d1" style="max-width:860px">
      <div class="mtile"><div class="k">${ic.cal()} Days</div><div class="v">${esc(config.walkIn.days)}</div></div>
      <div class="mtile accent"><div class="k">${ic.clk('#f04f33')} Time</div><div class="v red">${esc(config.walkIn.time)}</div></div>
      <div class="mtile"><div class="k">${ic.phone()} Call Ahead</div><div class="v"><a href="tel:${c.phone}" style="color:inherit">${esc(c.phoneDisplay)}</a></div></div>
      <div class="mtile"><div class="k">${ic.pin()} Venue</div><div class="v">${esc(c.locality)}</div></div>
    </div>
    <div class="spec-list rv" style="max-width:860px;margin-top:20px">
      <div class="spec-row"><span class="k">Address</span><span class="v">${esc(c.streetAddress)}, ${esc(c.locality)}, ${esc(c.region)} ${esc(c.postalCode)}</span></div>
    </div>
  </div>
</section>` : ''}
${others.length ? `
<div class="seam"><div class="burn"></div><div class="torch"></div></div>

<section id="other-roles">
  <div class="wrap">
    <div class="eyebrow rv"><span class="idx">&raquo;</span> Other Openings</div>
    <h2 class="steel rv">More Ways To <span class="red-word">Join.</span></h2>
    <div class="jgrid" style="margin-top:30px">
${others.map((o, i) => {
  const p = salaryText(o);
  return `      <article class="jcard rv${i ? ' rv-d1' : ''}" data-href="${jobUrl(o)}" tabindex="0" role="link" aria-label="${esc(o.title)}">
        <div class="glow"></div>
        <div class="jc-head">${mono(o.company)}${o.experience ? `<span class="jc-exp">${esc(o.experience)}</span>` : ''}</div>
        <h3 class="jc-title">${esc(o.title)}</h3>
        <p class="jc-sum">${o.summary}</p>
        <div class="jc-spec">
          <div class="jc-row"><span class="k">Location</span><span class="v">${esc(companies[o.company].shortLocation)}</span></div>${p ? `
          <div class="jc-row"><span class="k">Salary</span><span class="v red">${p}</span></div>` : ''}
        </div>
        <span class="jc-go">View Role &amp; Apply</span>
      </article>`;
}).join('\n')}
    </div>
  </div>
</section>` : ''}

<div class="seam"><div class="burn"></div><div class="torch"></div></div>

${nextNav(jobUrl(j))}

<div class="stickybar" id="sbar">
  <div class="wrap sb-in">
    <div class="sb-t"><b>${esc(j.title)}</b><span>${esc(c.shortLocation)}${pay ? ' &middot; ' + pay : ''}</span></div>
    <a class="btn btn-red" href="#apply">Apply Now</a>
  </div>
</div>`;

  return shell({
    title: `${esc(j.title)} | ${esc(c.name)} | Ferrous Group Careers`,
    ogTitle: `${esc(j.title)} | ${esc(c.name)}`,
    desc: `${esc(plain(j.summary))} ${esc(c.shortLocation)}.${pay ? ' ' + esc(pay) + '.' : ''} Apply online or walk in.`,
    url: SITE + jobUrl(j),
    ld: `<script type="application/ld+json">\n${JSON.stringify(ld)}\n</script>\n`,
    body,
    scripts: `<script>
(function(){
  document.querySelectorAll('.jcard[data-href]').forEach(function(c){
    var go=function(){location.href=c.dataset.href};
    c.addEventListener('click',go);
    c.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();go()}});
  });
  var bar=document.getElementById('sbar'),ap=document.getElementById('apply');
  if(bar&&ap){
    var tick=function(){
      var past=scrollY>620, atForm=ap.getBoundingClientRect().top<innerHeight*0.9;
      bar.classList.toggle('show',past&&!atForm);
    };
    addEventListener('scroll',tick,{passive:true});tick();
  }
})();
</script>
${hasForm(config.tallyFormId) ? TALLY_JS : ''}`
  });
}

JOBS.forEach(j => write(`careers/${j.slug}/index.html`, jobPage(j)));

/* prune pages whose role is no longer live */
const cdir = path.join(ROOT, 'careers');
if (fs.existsSync(cdir)) {
  const keep = new Set(JOBS.map(j => j.slug));
  fs.readdirSync(cdir, { withFileTypes: true })
    .filter(e => e.isDirectory() && !keep.has(e.name))
    .forEach(e => { fs.rmSync(path.join(cdir, e.name), { recursive: true, force: true });
                    console.log('  removed careers/' + e.name + ' (no longer live)'); });
}

/* ---------------- sitemap ---------------- */
console.log('\nGenerating sitemap...');
const today = new Date().toISOString().slice(0, 10);
const urls = [
  { u: SITE + '/',        p: '1.0', f: 'monthly' },
  { u: SITE + '/fe',      p: '0.9', f: 'monthly' },
  { u: SITE + '/de',      p: '0.9', f: 'monthly' },
  { u: SITE + '/fapl',    p: '0.9', f: 'monthly' },
  { u: SITE + '/careers', p: '0.8', f: 'weekly'  },
  ...JOBS.map(j => ({ u: SITE + jobUrl(j), p: '0.7', f: 'weekly' }))
];
write('sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map(x => `  <url><loc>${x.u}</loc><lastmod>${today}</lastmod><changefreq>${x.f}</changefreq><priority>${x.p}</priority></url>`).join('\n')}
</urlset>
`);

console.log(`\n  Done. ${JOBS.length} live role${JOBS.length === 1 ? '' : 's'}.`);
JOBS.forEach(j => console.log(`    ${j.title}  ->  ${jobUrl(j)}`));
const off = DATA.jobs.length - JOBS.length;
if (off) console.log(`  ${off} not live, excluded everywhere.`);
console.log('');
